# Generated by Django 3.0.6 on 2020-06-30 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('active', models.BooleanField(default=True)),
                ('idstr', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(default='', max_length=60)),
                ('heartrate', models.BigIntegerField(default=1593541614.0949981, editable=False)),
                ('down', models.BooleanField(default=True, editable=False)),
                ('ip', models.CharField(default='No IP yet', editable=False, max_length=60)),
                ('recipient1', models.EmailField(default='', max_length=254)),
                ('recipient2', models.EmailField(default='', max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
