# Generated by Django 3.0.6 on 2020-06-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='heartrate',
            field=models.BigIntegerField(default=1593542733.502672, editable=False),
        ),
        migrations.AlterField(
            model_name='host',
            name='recipient2',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
