# Generated by Django 3.0.6 on 2020-06-28 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='heartrate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
