# Generated by Django 3.0.6 on 2020-06-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0003_host_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='heartrate',
        ),
    ]
