# Generated by Django 3.0.6 on 2020-06-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0004_remove_host_heartrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='heartrate',
            field=models.DateField(auto_now=True),
        ),
    ]
