# Generated by Django 3.0.6 on 2020-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0005_host_heartrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='heartrate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
