# Generated by Django 3.0.6 on 2020-06-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0006_auto_20200628_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='down',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
