# Generated by Django 3.0.6 on 2020-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0007_host_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='heartrate',
            field=models.BigIntegerField(default=1593357090.7365532, editable=False),
        ),
    ]
