# Generated by Django 3.0.6 on 2020-06-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shbm_api', '0008_auto_20200628_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.CharField(default='null', editable=False, max_length=60),
        ),
        migrations.AlterField(
            model_name='host',
            name='heartrate',
            field=models.BigIntegerField(default=1593370762.7323816, editable=False),
        ),
    ]
